apiVersion: v1
kind: Service
metadata:
  name: appointments-service
  labels:
    app: appointments-deployment
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8088
  selector:
    app: appointments-deployment
